### PR TITLE
changes to the help commands [bot name] -> hubot (works when bot is not called hubot)

### PR DESCRIPTION
**Pull request by tenfourty**
[bot name] how am i? - details about the current channel + you
[bot name] sentiment - lists sentiment stats
[bot name] where's happiness? - which rooms are happiest?
[bot name] where's stress? - which rooms are stressed out?
[bot name] who's happy? - who's happiest?
[bot name] who's stressed? - who's stressed out?
chatbot adapter - Reply with the adapter

we now use hubot so we get a nicer output:
chatbot adapter - Reply with the adapter
chatbot how am i? - details about the current channel + you
chatbot sentiment - lists sentiment stats
chatbot where's happiness? - which rooms are happiest?
chatbot where's stress? - which rooms are stressed out?
chatbot who's happy? - who's happiest?
chatbot who's stressed? - who's stressed out?

### CODE REVIEW

**Comment by stephenyeargin** [comment]
:+1:

**Comment by tenfourty** [comment]
any chance of this PR being accepted?

**Comment by stephenyeargin** [comment]
@michikono doesn't seem to be a watcher on the repository anymore :cry:

**Comment by michikono** [comment]
Oops, sorry. Too many subscribed threads and didn't see this.

**Comment by tenfourty** [comment]
Thanks @michikono!

**Pull request merged**
